services:
  - type: web
    name: burol-sms-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SEMAPHORE_API_KEY
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_SENDER_EMAIL
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
